# Builds the Frontend of the application inside a node image
FROM node:lts-buster

# Install the dependencies
WORKDIR /app
COPY ./frontend/package.json ./frontend/package-lock.json /app/
RUN npm install

# Copy the frontend files, as they're only refreshed with frontend refresh
COPY ./frontend/. /app

# NOTE:
# - from now on we'll proceed with copy of the generated code from the Converter container and with the build
#   (the glue code will be copied to instantiated container's overlay's as it changes frequently)
