# Notebook converter: Notebooks -> Assets (pictures and HTML and JS-loader)
FROM python:3.7-buster

# place ourselves in /app
WORKDIR /app
RUN mkdir -p /app/input /app/output

# install the dependencies
COPY ./backend-converter/requirements.txt .
RUN pip install -r requirements.txt

# copy the conversion program
COPY ./backend-converter/convert-ipynb.py .
